name: Generate mario animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout repository with README
        uses: actions/checkout@v4

      - name: Clone mario generator
        run: |
          git clone https://github.com/juliano-cassimiro-quality/mario-contribution-graph.git generator
          cd generator
          npm install || echo "sem dependências"
          npm run build
          mkdir -p ../dist
          cp dist/mario-contribution-graph.svg ../dist/

      - name: push mario-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-mario
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
